//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCTTHTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHat()
        {
            this.CTVT_TS = new HashSet<CTVT_TS>();
            this.CTVT_TS1 = new HashSet<CTVT_TS>();
        }
    
        public int MaBH { get; set; }
        public string TenBH { get; set; }
        public string Nhac { get; set; }
        public string Loi { get; set; }
        public Nullable<int> Ma_CD { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTVT_TS> CTVT_TS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTVT_TS> CTVT_TS1 { get; set; }
    }
}
