//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCTTHTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTVT_TS
    {
        public int Ma_VT { get; set; }
        public int SBD { get; set; }
        public Nullable<int> BaiHatBB { get; set; }
        public Nullable<int> DiemBHBB { get; set; }
        public Nullable<int> BaiHatTC { get; set; }
        public Nullable<int> DiemBHTC { get; set; }
    
        public virtual BaiHat BaiHat { get; set; }
        public virtual BaiHat BaiHat1 { get; set; }
        public virtual ThiSinh ThiSinh { get; set; }
        public virtual VongThi VongThi { get; set; }
    }
}
