//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCTTHTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTVT_DT
    {
        public int Ma_VT { get; set; }
        public int LT { get; set; }
        public string DiaDiemThi { get; set; }
        public string ThoiGianThi { get; set; }
        public string DiaDiemTap { get; set; }
        public string ThoiGianTap { get; set; }
        public Nullable<int> Ma_GT { get; set; }
    
        public virtual DotThi DotThi { get; set; }
        public virtual GiaiThuong GiaiThuong { get; set; }
        public virtual VongThi VongThi { get; set; }
    }
}
