//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCTTHTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaTaiTro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaTaiTro()
        {
            this.CTTTDTs = new HashSet<CTTTDT>();
        }
    
        public int MaNTT { get; set; }
        public string TenNTT { get; set; }
        public string DiaChiNTT { get; set; }
        public string EmailNTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTTDT> CTTTDTs { get; set; }
    }
}
